dat<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(dat) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
dat$dateTime <- strptime( paste(dat$Date,dat$Time), format="%d/%m/%Y %H:%M:%S")
dev.copy(png,file="plot4.png", width=480,height=480)
par(mfrow=c(2,2))
dat$dateTime <- strptime( paste(dat$Date,dat$Time), format="%d/%m/%Y %H:%M:%S")
plot(dat[,10],dat[,3],type="l",ylab="Global Active Power(kilowats)",xlab="")
plot(dat[,10],dat[,5],type="l",ylab="Voltage",xlab="datetime")
plot (dat[,10],dat[,7],type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (dat[,10],dat[,8],type = "l", col = "red")
points (dat[,10],dat[,9],type = "l", col = "blue")
legend("topright", lty = 1,col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),bty="n")
plot(dat[,10],dat[,4],type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
