data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(data) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
data$dateTime <- strptime( paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
dev.copy(png,file="plot3.png", width=480,height=480)
plot (data[,10],data[,7],type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (data[,10],data[,8],type = "l", col = "red")
points (data[,10],data[,9],type = "l", col = "blue")
legend("topright", lty = 1,inset=0.05, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()

