data<-read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'),header=F, sep=';')
colnames(data) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
data$dateTime <- strptime( paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
dev.copy(png,file="plot4.png", width=480,height=480)
par(mfrow=c(2,2))
data$dateTime <- strptime( paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
plot(data[,10],data[,3],type="l",ylab="Global Active Power(kilowats)",xlab="")
plot(data[,10],data[,5],type="l",ylab="Voltage",xlab="datetime")
plot (data[,10],data[,7],type = "l", xlab = "", ylab = "Energy sub metering", col = "black")
lines (data[,10],data[,8],type = "l", col = "red")
points (data[,10],data[,9],type = "l", col = "blue")
legend("topright", lty = 1,col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"),bty="n")
plot(data[,10],data[,4],type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
